"""EPL Cloud Provider Deploy Commands Generator (v1.0)

Generates deployment configs and scripts for major cloud providers:
- AWS  : ECS task definition, ECR push script, ECS service config
- GCP  : Cloud Run deploy script, Cloud Build config
- Azure: Container Apps config, Azure CLI deploy script

Usage via CLI:
    epl deploy --aws   --image myapp:latest --region us-east-1
    epl deploy --gcp   --image myapp:latest --region us-central1
    epl deploy --azure --image myapp:latest --region eastus
"""

import os
import json
import textwrap


# ═══════════════════════════════════════════════════════════
# AWS — ECS + ECR
# ═══════════════════════════════════════════════════════════

def generate_ecr_push_script(app_name: str, image: str,
                               region: str = "us-east-1",
                               account_id: str = "YOUR_ACCOUNT_ID") -> str:
    """Generate a shell script to build and push image to AWS ECR."""
    return textwrap.dedent(f"""\
        #!/bin/bash
        # ECR Push Script for {app_name}
        # Generated by EPL Cloud Deploy
        #
        # Usage: chmod +x ecr-push.sh && ./ecr-push.sh

        set -e

        APP_NAME="{app_name}"
        IMAGE="{image}"
        REGION="{region}"
        ACCOUNT_ID="{account_id}"
        ECR_REPO="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$APP_NAME"

        echo "Logging in to ECR..."
        aws ecr get-login-password --region $REGION | \\
            docker login --username AWS --password-stdin $ECR_REPO

        echo "Creating ECR repository if it doesn't exist..."
        aws ecr describe-repositories --repository-names $APP_NAME \\
            --region $REGION 2>/dev/null || \\
            aws ecr create-repository --repository-name $APP_NAME \\
            --region $REGION

        echo "Building Docker image..."
        docker build -t $APP_NAME .

        echo "Tagging image..."
        docker tag $APP_NAME:latest $ECR_REPO:latest

        echo "Pushing image to ECR..."
        docker push $ECR_REPO:latest

        echo "Done! Image pushed to: $ECR_REPO:latest"
    """)


def generate_ecs_task_definition(app_name: str, image: str,
                                  port: int = 8000,
                                  region: str = "us-east-1",
                                  account_id: str = "YOUR_ACCOUNT_ID",
                                  cpu: str = "256",
                                  memory: str = "512") -> str:
    """Generate an ECS Fargate task definition JSON."""
    task_def = {
        "family": app_name,
        "networkMode": "awsvpc",
        "requiresCompatibilities": ["FARGATE"],
        "cpu": cpu,
        "memory": memory,
        "executionRoleArn": f"arn:aws:iam::{account_id}:role/ecsTaskExecutionRole",
        "containerDefinitions": [
            {
                "name": app_name,
                "image": f"{account_id}.dkr.ecr.{region}.amazonaws.com/{image}",
                "portMappings": [
                    {
                        "containerPort": port,
                        "protocol": "tcp"
                    }
                ],
                "essential": True,
                "environment": [
                    {"name": "EPL_ENV", "value": "production"},
                    {"name": "EPL_PORT", "value": str(port)}
                ],
                "logConfiguration": {
                    "logDriver": "awslogs",
                    "options": {
                        "awslogs-group": f"/ecs/{app_name}",
                        "awslogs-region": region,
                        "awslogs-stream-prefix": "ecs"
                    }
                },
                "healthCheck": {
                    "command": [
                        "CMD-SHELL",
                        f"curl -f http://localhost:{port}/_health || exit 1"
                    ],
                    "interval": 30,
                    "timeout": 5,
                    "retries": 3,
                    "startPeriod": 15
                }
            }
        ]
    }
    return json.dumps(task_def, indent=2)


def generate_ecs_service(app_name: str,
                          cluster: str = "epl-cluster",
                          desired_count: int = 2,
                          subnet_id: str = "YOUR_SUBNET_ID",
                          security_group: str = "YOUR_SG_ID") -> str:
    """Generate an ECS service config JSON."""
    service = {
        "cluster": cluster,
        "serviceName": f"{app_name}-service",
        "taskDefinition": app_name,
        "desiredCount": desired_count,
        "launchType": "FARGATE",
        "networkConfiguration": {
            "awsvpcConfiguration": {
                "subnets": [subnet_id],
                "securityGroups": [security_group],
                "assignPublicIp": "ENABLED"
            }
        },
        "deploymentConfiguration": {
            "minimumHealthyPercent": 50,
            "maximumPercent": 200
        }
    }
    return json.dumps(service, indent=2)


def generate_aws_all(app_name: str, image: str,
                      output_dir: str = "./deploy/aws",
                      port: int = 8000, region: str = "us-east-1",
                      account_id: str = "YOUR_ACCOUNT_ID") -> list:
    """Generate all AWS deployment files."""
    os.makedirs(output_dir, exist_ok=True)

    files = {
        "ecr-push.sh": generate_ecr_push_script(
            app_name, image, region, account_id),
        "task-definition.json": generate_ecs_task_definition(
            app_name, image, port, region, account_id),
        "ecs-service.json": generate_ecs_service(app_name),
    }

    written = []
    for filename, content in files.items():
        path = os.path.join(output_dir, filename)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        written.append(path)

    return written


# ═══════════════════════════════════════════════════════════
# GCP — Cloud Run
# ═══════════════════════════════════════════════════════════

def generate_cloudrun_deploy_script(app_name: str, image: str,
                                     region: str = "us-central1",
                                     project_id: str = "YOUR_PROJECT_ID",
                                     port: int = 8000) -> str:
    """Generate a Cloud Run deploy shell script."""
    return textwrap.dedent(f"""\
        #!/bin/bash
        # Cloud Run Deploy Script for {app_name}
        # Generated by EPL Cloud Deploy
        #
        # Usage: chmod +x cloudrun-deploy.sh && ./cloudrun-deploy.sh

        set -e

        APP_NAME="{app_name}"
        IMAGE="{image}"
        REGION="{region}"
        PROJECT_ID="{project_id}"
        PORT="{port}"

        echo "Configuring gcloud project..."
        gcloud config set project $PROJECT_ID

        echo "Enabling required APIs..."
        gcloud services enable run.googleapis.com
        gcloud services enable containerregistry.googleapis.com

        echo "Building and pushing image..."
        gcloud builds submit --tag gcr.io/$PROJECT_ID/$APP_NAME

        echo "Deploying to Cloud Run..."
        gcloud run deploy $APP_NAME \\
            --image gcr.io/$PROJECT_ID/$APP_NAME \\
            --platform managed \\
            --region $REGION \\
            --port $PORT \\
            --allow-unauthenticated \\
            --min-instances 1 \\
            --max-instances 10 \\
            --memory 512Mi \\
            --cpu 1 \\
            --set-env-vars EPL_ENV=production,EPL_PORT=$PORT

        echo "Getting service URL..."
        gcloud run services describe $APP_NAME \\
            --region $REGION \\
            --format "value(status.url)"

        echo "Deployment complete!"
    """)


def generate_cloudbuild_yaml(app_name: str,
                              project_id: str = "YOUR_PROJECT_ID") -> str:
    """Generate a Cloud Build config."""
    return textwrap.dedent(f"""\
        # Cloud Build configuration for {app_name}
        # Generated by EPL Cloud Deploy
        #
        # Usage: gcloud builds submit

        steps:
          - name: "gcr.io/cloud-builders/docker"
            args:
              - "build"
              - "-t"
              - "gcr.io/{project_id}/{app_name}:$COMMIT_SHA"
              - "-t"
              - "gcr.io/{project_id}/{app_name}:latest"
              - "."

          - name: "gcr.io/cloud-builders/docker"
            args:
              - "push"
              - "gcr.io/{project_id}/{app_name}:$COMMIT_SHA"

          - name: "gcr.io/cloud-builders/docker"
            args:
              - "push"
              - "gcr.io/{project_id}/{app_name}:latest"

          - name: "gcr.io/cloud-builders/gcloud"
            args:
              - "run"
              - "deploy"
              - "{app_name}"
              - "--image"
              - "gcr.io/{project_id}/{app_name}:$COMMIT_SHA"
              - "--platform"
              - "managed"
              - "--region"
              - "us-central1"

        images:
          - "gcr.io/{project_id}/{app_name}:$COMMIT_SHA"
          - "gcr.io/{project_id}/{app_name}:latest"
    """)


def generate_gcp_all(app_name: str, image: str,
                      output_dir: str = "./deploy/gcp",
                      port: int = 8000, region: str = "us-central1",
                      project_id: str = "YOUR_PROJECT_ID") -> list:
    """Generate all GCP deployment files."""
    os.makedirs(output_dir, exist_ok=True)

    files = {
        "cloudrun-deploy.sh": generate_cloudrun_deploy_script(
            app_name, image, region, project_id, port),
        "cloudbuild.yaml": generate_cloudbuild_yaml(app_name, project_id),
    }

    written = []
    for filename, content in files.items():
        path = os.path.join(output_dir, filename)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        written.append(path)

    return written


# ═══════════════════════════════════════════════════════════
# Azure — Container Apps
# ═══════════════════════════════════════════════════════════

def generate_azure_containerapp(app_name: str, image: str,
                                  port: int = 8000,
                                  region: str = "eastus") -> str:
    """Generate Azure Container Apps YAML config."""
    return textwrap.dedent(f"""\
        # Azure Container Apps configuration for {app_name}
        # Generated by EPL Cloud Deploy
        #
        # Usage: az containerapp create --yaml containerapp.yaml

        name: {app_name}
        location: {region}
        resourceGroup: {app_name}-rg
        type: Microsoft.App/containerApps
        properties:
          managedEnvironmentId: /subscriptions/YOUR_SUBSCRIPTION_ID/resourceGroups/{app_name}-rg/providers/Microsoft.App/managedEnvironments/{app_name}-env
          configuration:
            ingress:
              external: true
              targetPort: {port}
              transport: http
            registries: []
          template:
            containers:
              - name: {app_name}
                image: {image}
                resources:
                  cpu: 0.5
                  memory: 1Gi
                env:
                  - name: EPL_ENV
                    value: production
                  - name: EPL_PORT
                    value: "{port}"
            scale:
              minReplicas: 1
              maxReplicas: 10
              rules:
                - name: http-scaling
                  http:
                    metadata:
                      concurrentRequests: "100"
    """)


def generate_azure_deploy_script(app_name: str, image: str,
                                   region: str = "eastus",
                                   port: int = 8000) -> str:
    """Generate Azure CLI deploy script."""
    return textwrap.dedent(f"""\
        #!/bin/bash
        # Azure Container Apps Deploy Script for {app_name}
        # Generated by EPL Cloud Deploy
        #
        # Usage: chmod +x azure-deploy.sh && ./azure-deploy.sh

        set -e

        APP_NAME="{app_name}"
        IMAGE="{image}"
        REGION="{region}"
        RESOURCE_GROUP="${{APP_NAME}}-rg"
        ENVIRONMENT="${{APP_NAME}}-env"
        PORT="{port}"

        echo "Creating resource group..."
        az group create --name $RESOURCE_GROUP --location $REGION

        echo "Creating Container Apps environment..."
        az containerapp env create \\
            --name $ENVIRONMENT \\
            --resource-group $RESOURCE_GROUP \\
            --location $REGION

        echo "Deploying container app..."
        az containerapp create \\
            --name $APP_NAME \\
            --resource-group $RESOURCE_GROUP \\
            --environment $ENVIRONMENT \\
            --image $IMAGE \\
            --target-port $PORT \\
            --ingress external \\
            --min-replicas 1 \\
            --max-replicas 10 \\
            --env-vars EPL_ENV=production EPL_PORT=$PORT

        echo "Getting app URL..."
        az containerapp show \\
            --name $APP_NAME \\
            --resource-group $RESOURCE_GROUP \\
            --query properties.configuration.ingress.fqdn \\
            --output tsv

        echo "Deployment complete!"
    """)


def generate_azure_all(app_name: str, image: str,
                        output_dir: str = "./deploy/azure",
                        port: int = 8000,
                        region: str = "eastus") -> list:
    """Generate all Azure deployment files."""
    os.makedirs(output_dir, exist_ok=True)

    files = {
        "containerapp.yaml": generate_azure_containerapp(
            app_name, image, port, region),
        "azure-deploy.sh": generate_azure_deploy_script(
            app_name, image, region, port),
    }

    written = []
    for filename, content in files.items():
        path = os.path.join(output_dir, filename)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        written.append(path)

    return written
