package com.epl.app

/**
 * EPL Runtime Support for Android
 * Generated by EPL Kotlin Generator v2.0
 */
object EPLRuntime {
    private val variables = mutableMapOf<String, Any?>()
    
    fun setVar(name: String, value: Any?) {
        variables[name] = value
    }
    
    fun getVar(name: String): Any? = variables[name]
    
    fun toText(value: Any?): String = when (value) {
        null -> "nothing"
        is Boolean -> if (value) "true" else "false"
        is Double -> if (value == value.toLong().toDouble()) value.toLong().toString() else value.toString()
        else -> value.toString()
    }
    
    fun toInteger(value: Any?): Long = when (value) {
        is Number -> value.toLong()
        is String -> value.toLongOrNull() ?: 0L
        is Boolean -> if (value) 1L else 0L
        else -> 0L
    }
    
    fun toDecimal(value: Any?): Double = when (value) {
        is Number -> value.toDouble()
        is String -> value.toDoubleOrNull() ?: 0.0
        is Boolean -> if (value) 1.0 else 0.0
        else -> 0.0
    }
    
    fun typeOf(value: Any?): String = when (value) {
        null -> "Nothing"
        is Long, is Int -> "Integer"
        is Double, is Float -> "Decimal"
        is String -> "String"
        is Boolean -> "Boolean"
        is List<*> -> "List"
        is Map<*, *> -> "Map"
        else -> value::class.simpleName ?: "Unknown"
    }
    
    fun length(value: Any?): Int = when (value) {
        is String -> value.length
        is List<*> -> value.size
        is Map<*, *> -> value.size
        else -> 0
    }
    
    // Math helpers
    fun power(base: Double, exp: Double): Double = Math.pow(base, exp)
    fun sqrt(x: Double): Double = Math.sqrt(x)
    fun abs(x: Double): Double = Math.abs(x)
    fun floor(x: Double): Double = Math.floor(x)
    fun ceil(x: Double): Double = Math.ceil(x)
    fun round(x: Double): Long = Math.rint(x).toLong()
    fun random(): Double = Math.random()
    fun randomInt(min: Int, max: Int): Int = (min..max).random()
    fun max(a: Double, b: Double): Double = maxOf(a, b)
    fun min(a: Double, b: Double): Double = minOf(a, b)

    // EPL `+`: numeric addition when both sides are numbers, string concat otherwise.
    // Used only for statically-dynamic operands (Any); typed operands compile to `+`.
    fun eplAdd(a: Any?, b: Any?): Any {
        if (a is Number && b is Number) {
            return if (a is Double || b is Double || a is Float || b is Float)
                a.toDouble() + b.toDouble()
            else a.toLong() + b.toLong()
        }
        return toText(a) + toText(b)
    }

    // EPL truthiness: null/false/0/empty-string/empty-collection are falsy.
    fun truthy(v: Any?): Boolean = when (v) {
        null -> false
        is Boolean -> v
        is Number -> v.toDouble() != 0.0
        is String -> v.isNotEmpty()
        is List<*> -> v.isNotEmpty()
        is Map<*, *> -> v.isNotEmpty()
        else -> true
    }

    // EPL `/`: raises the interpreter-formatted error on a zero divisor and,
    // like the interpreter, keeps an evenly-divisible int/int result integral.
    fun eplDiv(a: Any?, b: Any?, line: Int = 0): Any {
        val x = a as Number
        val y = b as Number
        if (y.toDouble() == 0.0)
            throw RuntimeException("EPL Runtime Error on line $line: Cannot divide by zero.")
        if (bothInt(x, y) && x.toLong() % y.toLong() == 0L) return x.toLong() / y.toLong()
        return x.toDouble() / y.toDouble()
    }

    // ─── Dynamic arithmetic/comparison (operands typed Any?, e.g. lambda params) ───
    private fun bothInt(a: Number, b: Number) =
        a !is Double && a !is Float && b !is Double && b !is Float
    fun eplMul(a: Any?, b: Any?): Any {
        val x = a as Number; val y = b as Number
        return if (bothInt(x, y)) x.toLong() * y.toLong() else x.toDouble() * y.toDouble()
    }
    fun eplSub(a: Any?, b: Any?): Any {
        val x = a as Number; val y = b as Number
        return if (bothInt(x, y)) x.toLong() - y.toLong() else x.toDouble() - y.toDouble()
    }
    fun eplMod(a: Any?, b: Any?): Any {
        val x = a as Number; val y = b as Number
        return if (bothInt(x, y)) x.toLong() % y.toLong() else x.toDouble() % y.toDouble()
    }
    fun eplPow(a: Any?, b: Any?): Any {
        val x = a as Number; val y = b as Number
        // int ** non-negative int stays integral (interpreter parity)
        if (bothInt(x, y) && y.toLong() >= 0) {
            var r = 1L
            repeat(y.toInt()) { r *= x.toLong() }
            return r
        }
        return Math.pow(x.toDouble(), y.toDouble())
    }
    private fun cmp(a: Any?, b: Any?): Int {
        if (a is Number && b is Number) return a.toDouble().compareTo(b.toDouble())
        if (a is String && b is String) return a.compareTo(b)
        throw RuntimeException("Cannot compare ${typeName(a)} and ${typeName(b)}.")
    }
    fun eplLt(a: Any?, b: Any?): Boolean = cmp(a, b) < 0
    fun eplGt(a: Any?, b: Any?): Boolean = cmp(a, b) > 0
    fun eplLe(a: Any?, b: Any?): Boolean = cmp(a, b) <= 0
    fun eplGe(a: Any?, b: Any?): Boolean = cmp(a, b) >= 0
    // EPL `==`: numbers compare by value across Int/Double; else structural.
    fun eplEq(a: Any?, b: Any?): Boolean {
        if (a is Number && b is Number) return a.toDouble() == b.toDouble()
        return a == b
    }

    // EPL truthiness: null/false/0/""/empty-collection are falsey (interpreter parity).
    fun eplTruthy(v: Any?): Boolean = when (v) {
        null -> false
        is Boolean -> v
        is Number -> v.toDouble() != 0.0
        is CharSequence -> v.isNotEmpty()
        is Collection<*> -> v.isNotEmpty()
        is Map<*, *> -> v.isNotEmpty()
        else -> true
    }

    // ─── Higher-order list methods (dynamic; mirror interpreter list callables) ───
    @Suppress("UNCHECKED_CAST")
    private fun asList(o: Any?): List<Any?> =
        o as? List<Any?> ?: throw RuntimeException("Expected a list.")
    fun mapList(o: Any?, fn: (Any?) -> Any?): MutableList<Any?> =
        asList(o).map(fn).toMutableList()
    fun filterList(o: Any?, fn: (Any?) -> Any?): MutableList<Any?> =
        asList(o).filter { eplTruthy(fn(it)) }.toMutableList()
    fun reduceList(o: Any?, fn: (Any?, Any?) -> Any?): Any? {
        val items = asList(o)
        if (items.isEmpty()) throw RuntimeException("reduce() called on empty list with no initial value.")
        var acc: Any? = items[0]
        for (i in 1 until items.size) acc = fn(acc, items[i])
        return acc
    }
    fun reduceList(o: Any?, fn: (Any?, Any?) -> Any?, init: Any?): Any? {
        var acc = init
        for (item in asList(o)) acc = fn(acc, item)
        return acc
    }
    fun findList(o: Any?, fn: (Any?) -> Any?): Any? =
        asList(o).firstOrNull { eplTruthy(fn(it)) }
    fun everyList(o: Any?, fn: (Any?) -> Any?): Boolean =
        asList(o).all { eplTruthy(fn(it)) }
    fun someList(o: Any?, fn: (Any?) -> Any?): Boolean =
        asList(o).any { eplTruthy(fn(it)) }

    // String helpers
    fun uppercase(s: String): String = s.uppercase()
    fun lowercase(s: String): String = s.lowercase()
    fun trim(s: String): String = s.trim()
    fun split(s: String, delim: String): List<String> = s.split(delim)
    fun join(list: List<*>, sep: String): String = list.joinToString(sep)
    fun replace(s: String, old: String, new: String): String = s.replace(old, new)
    fun contains(s: String, sub: String): Boolean = s.contains(sub)
    fun startsWith(s: String, prefix: String): Boolean = s.startsWith(prefix)
    fun endsWith(s: String, suffix: String): Boolean = s.endsWith(suffix)
    fun substring(s: String, start: Int, end: Int): String = s.substring(start, minOf(end, s.length))

    // ─── EPL string methods (mirror interpreter _call_string_method) ───
    fun strCount(s: String, sub: String): Int {
        if (sub.isEmpty()) return 0
        var count = 0
        var i = s.indexOf(sub)
        while (i >= 0) { count++; i = s.indexOf(sub, i + sub.length) }
        return count
    }
    fun padLeft(s: String, width: Int, fill: String = " "): String =
        s.padStart(width, if (fill.isEmpty()) ' ' else fill[0])
    fun padRight(s: String, width: Int, fill: String = " "): String =
        s.padEnd(width, if (fill.isEmpty()) ' ' else fill[0])
    fun charAt(s: String, idx: Int): String {
        if (idx < 0 || idx >= s.length) throw RuntimeException("Index $idx out of range.")
        return s[idx].toString()
    }
    fun toCharList(s: String): MutableList<String> =
        s.map { it.toString() }.toMutableList()
    fun isNumberStr(s: String): Boolean = s.toDoubleOrNull() != null
    fun isAlphaStr(s: String): Boolean = s.isNotEmpty() && s.all { it.isLetter() }
    fun strFormat(s: String, vararg args: Any?): String {
        var result = s
        for (a in args) result = result.replaceFirst("{}", a?.toString() ?: "nothing")
        return result
    }
    fun reversed(obj: Any?): Any? = when (obj) {
        is CharSequence -> obj.reversed().toString()
        is List<*> -> obj.reversed().toMutableList()
        else -> throw RuntimeException("reversed() expects a list or text.")
    }

    // ─── EPL collection/number/type builtins (free functions) ───
    fun rangeOf(end: Int): MutableList<Int> = (0 until end).toMutableList()
    fun rangeOf(start: Int, end: Int): MutableList<Int> = (start until end).toMutableList()
    fun rangeOf(start: Int, end: Int, step: Int): MutableList<Int> {
        if (step == 0) throw RuntimeException("range() step cannot be zero.")
        val out = ArrayList<Int>()
        var i = start
        if (step > 0) while (i < end) { out.add(i); i += step }
        else while (i > end) { out.add(i); i += step }
        return out
    }
    fun sumOf(list: Any?): Any? {
        val items = list as List<*>
        if (items.all { it is Int }) return items.sumOf { it as Int }
        return items.sumOf { (it as Number).toDouble() }
    }
    @Suppress("UNCHECKED_CAST")
    fun sortedOf(list: Any?): MutableList<Any?> {
        val items = (list as List<*>).toMutableList()
        (items as MutableList<Comparable<Any?>>).sort()
        return items as MutableList<Any?>
    }
    fun isInteger(v: Any?): Boolean = v is Int || v is Long
    fun isDecimal(v: Any?): Boolean = v is Double || v is Float
    fun isText(v: Any?): Boolean = v is CharSequence
    fun isBoolean(v: Any?): Boolean = v is Boolean
    fun isList(v: Any?): Boolean = v is List<*>
    fun isMap(v: Any?): Boolean = v is Map<*, *>
    fun isNothing(v: Any?): Boolean = v == null
    fun isNumber(v: Any?): Boolean = v is Int || v is Long || v is Double || v is Float
    fun charCode(s: Any?): Int {
        val str = s as String
        if (str.length != 1) throw RuntimeException("char_code() takes 1 single-character text argument.")
        return str[0].code
    }
    fun fromCharCode(n: Any?): String = (n as Number).toInt().toChar().toString()
    fun jsonParse(s: Any?): Any? = jsonToEpl(org.json.JSONTokener(s as String).nextValue())
    private fun jsonToEpl(v: Any?): Any? = when (v) {
        is org.json.JSONObject -> {
            val m = LinkedHashMap<String, Any?>()
            for (k in v.keys()) m[k] = jsonToEpl(v.get(k))
            m
        }
        is org.json.JSONArray -> {
            val l = ArrayList<Any?>()
            for (i in 0 until v.length()) l.add(jsonToEpl(v.get(i)))
            l
        }
        org.json.JSONObject.NULL -> null
        else -> v
    }
    fun jsonStringify(v: Any?): String = eplToJson(v).toString()
    private fun eplToJson(v: Any?): Any? = when (v) {
        is Map<*, *> -> {
            val o = org.json.JSONObject()
            for ((k, vv) in v) o.put(k.toString(), eplToJson(vv))
            o
        }
        is List<*> -> {
            val a = org.json.JSONArray()
            for (it in v) a.put(eplToJson(it))
            a
        }
        null -> org.json.JSONObject.NULL
        else -> v
    }

    // ─── Crypto / encoding native builtins ───
    fun hashSha256(text: String): String {
        val d = java.security.MessageDigest.getInstance("SHA-256").digest(text.toByteArray(Charsets.UTF_8))
        return d.joinToString("") { "%02x".format(it) }
    }
    fun hashMd5(text: String): String {
        val d = java.security.MessageDigest.getInstance("MD5").digest(text.toByteArray(Charsets.UTF_8))
        return d.joinToString("") { "%02x".format(it) }
    }
    fun base64Encode(text: String): String =
        android.util.Base64.encodeToString(text.toByteArray(Charsets.UTF_8), android.util.Base64.NO_WRAP)
    fun base64Decode(text: String): String =
        String(android.util.Base64.decode(text, android.util.Base64.NO_WRAP), Charsets.UTF_8)
    fun hexEncode(text: String): String =
        text.toByteArray(Charsets.UTF_8).joinToString("") { "%02x".format(it) }
    fun hexDecode(hex: String): String {
        val bytes = ByteArray(hex.length / 2) { i ->
            hex.substring(i * 2, i * 2 + 2).toInt(16).toByte()
        }
        return String(bytes, Charsets.UTF_8)
    }
    fun urlEncode(text: String): String = java.net.URLEncoder.encode(text, "UTF-8")
    fun urlDecode(text: String): String = java.net.URLDecoder.decode(text, "UTF-8")
    fun uuid4(): String = java.util.UUID.randomUUID().toString()

    // ─── Datetime native builtins ───
    fun timestamp(): Double = System.currentTimeMillis() / 1000.0
    fun today(): String = java.time.LocalDate.now().toString()
    fun now(): String = java.time.LocalDateTime.now().toString()

    // ─── Regex native builtins ───
    fun regexFindAll(pattern: String, text: String): MutableList<String> {
        val out = ArrayList<String>()
        val m = java.util.regex.Pattern.compile(pattern).matcher(text)
        while (m.find()) out.add(m.group())
        return out
    }
    fun regexTest(pattern: String, text: String): Boolean =
        java.util.regex.Pattern.compile(pattern).matcher(text).find()
    fun regexReplace(pattern: String, replacement: String, text: String): String =
        java.util.regex.Pattern.compile(pattern).matcher(text).replaceAll(java.util.regex.Matcher.quoteReplacement(replacement))
    fun regexSplit(pattern: String, text: String): MutableList<String> =
        java.util.regex.Pattern.compile(pattern).split(text, -1).toMutableList()

    // ─── Math native builtins ───
    fun factorial(n: Any?): Long {
        var r = 1L
        for (i in 2..(n as Number).toInt()) r *= i
        return r
    }
    fun gcd(a: Any?, b: Any?): Long {
        var x = (a as Number).toLong(); var y = (b as Number).toLong()
        while (y != 0L) { val t = y; y = x % y; x = t }
        return kotlin.math.abs(x)
    }

    // ─── Collections native builtins ───
    @Suppress("UNCHECKED_CAST")
    fun listPop(list: Any?): Any? {
        val items = list as MutableList<Any?>
        if (items.isEmpty()) return null
        return items.removeAt(items.size - 1)
    }
    @Suppress("UNCHECKED_CAST")
    fun listAdd(list: Any?, item: Any?): Any? {
        (list as MutableList<Any?>).add(item)
        return list
    }
    @Suppress("UNCHECKED_CAST")
    fun listRemove(list: Any?, item: Any?): Any? {
        (list as MutableList<Any?>).remove(item)
        return list
    }
    fun dictFromLists(keys: Any?, values: Any?): MutableMap<Any?, Any?> {
        val ks = keys as List<*>
        val vs = values as List<*>
        val out = LinkedHashMap<Any?, Any?>()
        for (i in ks.indices) out[ks[i]] = if (i < vs.size) vs[i] else null
        return out
    }

    // ─── Dynamic access (EPL maps, lists, db rows) ───
    fun field(obj: Any?, name: String): Any? = when {
        name == "length" || name == "size" -> lengthOf(obj)
        obj is Map<*, *> -> obj[name]
        else -> null
    }

    fun at(obj: Any?, index: Any?): Any? = when (obj) {
        is List<*> -> obj[(index as Number).toInt()]
        is Map<*, *> -> obj[index]
        is String -> obj[(index as Number).toInt()].toString()
        else -> null
    }

    fun lengthOf(obj: Any?): Int = when (obj) {
        is CharSequence -> obj.length
        is Map<*, *> -> obj.size
        is Collection<*> -> obj.size
        else -> 0
    }

    // ─── Dynamic receivers shared by strings and lists (static type unknown) ───
    @Suppress("UNCHECKED_CAST")
    fun iterate(obj: Any?): List<Any> = when (obj) {
        is CharSequence -> obj.map { it.toString() }
        is Collection<*> -> obj.toList() as List<Any>
        is Map<*, *> -> obj.keys.toList() as List<Any>
        else -> throw RuntimeException("Value of type ${typeName(obj)} is not iterable.")
    }
    fun reverseOf(obj: Any?): Any = when (obj) {
        is CharSequence -> obj.reversed().toString()
        is List<*> -> obj.reversed().toMutableList()
        else -> throw RuntimeException("Cannot reverse a ${typeName(obj)}.")
    }
    fun countOf(obj: Any?, target: Any?): Int = when (obj) {
        is CharSequence -> if (target is CharSequence && target.isNotEmpty())
            Regex(Regex.escape(target.toString())).findAll(obj).count() else 0
        is Collection<*> -> obj.count { it == target }
        else -> 0
    }
    fun replaceOf(obj: Any?, from: Any?, to: Any?): Any = when (obj) {
        is CharSequence -> obj.toString().replace(from.toString(), to.toString())
        else -> throw RuntimeException("Cannot replace on a ${typeName(obj)}.")
    }
    fun containsOf(obj: Any?, target: Any?): Boolean = when (obj) {
        is CharSequence -> obj.contains(target.toString())
        is Collection<*> -> obj.contains(target)
        is Map<*, *> -> obj.containsKey(target)
        else -> false
    }

    fun roundNum(x: Any?): Long = Math.rint((x as Number).toDouble()).toLong()
    fun roundNum(x: Any?, digits: Any?): Double =
        java.math.BigDecimal.valueOf((x as Number).toDouble())
            .setScale((digits as Number).toInt(), java.math.RoundingMode.HALF_EVEN).toDouble()

    // abs(): keeps an integer integral and a decimal decimal (interpreter parity).
    fun absNum(x: Any?): Any = when (x) {
        is Int -> kotlin.math.abs(x)
        is Long -> kotlin.math.abs(x)
        is Double -> kotlin.math.abs(x)
        is Float -> kotlin.math.abs(x)
        is Number -> kotlin.math.abs(x.toDouble())
        else -> throw RuntimeException("abs() expects a number.")
    }

    fun typeName(v: Any?): String = when (v) {
        null -> "nothing"
        is Boolean -> "boolean"
        is Int, is Long -> "integer"
        is Double, is Float -> "decimal"
        is CharSequence -> "text"
        is Map<*, *> -> "map"
        is List<*> -> "list"
        else -> "object"
    }

    // Python-style slicing (start/end/step may be null); mirrors EPL's obj[a:b:c].
    private fun sliceIndices(n: Int, startA: Any?, stopA: Any?, step: Int): List<Int> {
        var start: Int
        var stop: Int
        if (startA == null) {
            start = if (step < 0) n - 1 else 0
        } else {
            start = (startA as Number).toInt()
            if (start < 0) start += n
            if (start < 0) start = if (step < 0) -1 else 0
            else if (start >= n) start = if (step < 0) n - 1 else n
        }
        if (stopA == null) {
            stop = if (step < 0) -1 else n
        } else {
            stop = (stopA as Number).toInt()
            if (stop < 0) stop += n
            if (stop < 0) stop = if (step < 0) -1 else 0
            else if (stop >= n) stop = if (step < 0) n - 1 else n
        }
        val out = ArrayList<Int>()
        var i = start
        if (step > 0) { while (i < stop) { out.add(i); i += step } }
        else { while (i > stop) { out.add(i); i += step } }
        return out
    }

    fun slice(obj: Any?, start: Any?, end: Any?, step: Any?): Any? {
        val st = (step as? Number)?.toInt() ?: 1
        if (st == 0) throw RuntimeException("slice step cannot be zero")
        return when (obj) {
            is List<*> -> sliceIndices(obj.size, start, end, st).map { obj[it] }.toMutableList()
            is CharSequence -> {
                val sb = StringBuilder()
                for (i in sliceIndices(obj.length, start, end, st)) sb.append(obj[i])
                sb.toString()
            }
            else -> null
        }
    }

    // ─── EPL map methods (dynamic receiver; mirrors interpreter dict methods) ───
    @Suppress("UNCHECKED_CAST")
    private fun asMap(o: Any?): MutableMap<String, Any?> =
        o as? MutableMap<String, Any?> ?: throw RuntimeException("Expected a map.")
    fun mapHas(o: Any?, key: Any?): Boolean = asMap(o).containsKey(key.toString())
    fun mapKeys(o: Any?): MutableList<String> = asMap(o).keys.toMutableList()
    fun mapValues(o: Any?): MutableList<Any?> = asMap(o).values.toMutableList()
    fun mapEntries(o: Any?): MutableList<MutableList<Any?>> =
        asMap(o).entries.map { mutableListOf(it.key as Any?, it.value) }.toMutableList()
    fun mapMerge(o: Any?, other: Any?): MutableMap<String, Any?> {
        val r = LinkedHashMap(asMap(o))
        r.putAll(asMap(other))
        return r
    }
    fun mapGet(o: Any?, key: Any?): Any? = asMap(o)[key.toString()]
    fun mapGet(o: Any?, key: Any?, default: Any?): Any? {
        val map = asMap(o)
        val k = key.toString()
        return if (map.containsKey(k)) map[k] else default
    }
    fun mapSet(o: Any?, key: Any?, value: Any?) { asMap(o)[key.toString()] = value }
    fun mapClear(o: Any?) { asMap(o).clear() }
    fun mapCopy(o: Any?): MutableMap<String, Any?> = LinkedHashMap(asMap(o))
    fun mapRemove(o: Any?, key: Any?) { asMap(o).remove(key.toString()) }

    // ─── SQLite bridge (db_* builtins) ───
    fun dbOpen(name: String): android.database.sqlite.SQLiteDatabase {
        val ctx = EPLApplication.instance.applicationContext
        return ctx.openOrCreateDatabase(name, android.content.Context.MODE_PRIVATE, null)
    }

    fun dbExecute(db: Any?, sql: String, params: List<Any?> = emptyList<Any?>()) {
        val database = db as android.database.sqlite.SQLiteDatabase
        if (params.isEmpty()) database.execSQL(sql)
        else database.execSQL(sql, params.toTypedArray())
    }

    fun dbQuery(
        db: Any?,
        sql: String,
        params: List<Any?> = emptyList<Any?>(),
    ): MutableList<Map<String, Any?>> {
        val database = db as android.database.sqlite.SQLiteDatabase
        val args = params.map { it?.toString() }.toTypedArray()
        val rows = mutableListOf<Map<String, Any?>>()
        database.rawQuery(sql, args).use { c ->
            while (c.moveToNext()) {
                val row = LinkedHashMap<String, Any?>()
                for (i in 0 until c.columnCount) {
                    row[c.getColumnName(i)] = when (c.getType(i)) {
                        android.database.Cursor.FIELD_TYPE_INTEGER -> c.getLong(i)
                        android.database.Cursor.FIELD_TYPE_FLOAT -> c.getDouble(i)
                        android.database.Cursor.FIELD_TYPE_NULL -> null
                        android.database.Cursor.FIELD_TYPE_BLOB -> c.getBlob(i)
                        else -> c.getString(i)
                    }
                }
                rows.add(row)
            }
        }
        return rows
    }

    fun dbQueryOne(
        db: Any?,
        sql: String,
        params: List<Any?> = emptyList<Any?>(),
    ): Map<String, Any?>? = dbQuery(db, sql, params).firstOrNull()

    fun dbCount(db: Any?, table: String): Long {
        val rows = dbQuery(db, "SELECT count(*) AS c FROM " + table)
        return (rows.firstOrNull()?.get("c") as? Number)?.toLong() ?: 0L
    }

    // Identifier + type validation mirrors the EPL interpreter (stdlib._db_create_table):
    // raw SQL column defs are rejected and every name/type component is whitelisted,
    // so a generated app is no more injection-prone than the interpreter.
    private val DB_IDENT = Regex("^[a-zA-Z_][a-zA-Z0-9_]*$")
    private val DB_SAFE_TYPE_WORDS = setOf(
        "TEXT", "INTEGER", "REAL", "BLOB", "NUMERIC", "DECIMAL", "FLOAT", "DOUBLE",
        "VARCHAR", "CHAR", "BOOLEAN", "DATE", "DATETIME", "TIMESTAMP", "PRIMARY",
        "KEY", "NOT", "NULL", "UNIQUE", "AUTOINCREMENT", "DEFAULT", "CHECK", "REFERENCES",
    )

    fun dbCreateTable(db: Any?, table: String, columns: Any?): Boolean {
        val database = db as android.database.sqlite.SQLiteDatabase
        if (!DB_IDENT.matches(table)) throw RuntimeException("Invalid table name: " + table)
        val cols = (columns as? Map<*, *>)
            ?: throw RuntimeException("db_create_table requires a map of name -> type.")
        val defs = StringBuilder()
        for ((rawName, rawType) in cols) {
            val name = rawName.toString()
            if (!DB_IDENT.matches(name)) throw RuntimeException("Invalid column name: " + name)
            val typ = rawType.toString()
            for (w in typ.uppercase().split(Regex("\\s+"))) {
                if (w.isEmpty()) continue
                val paren = w.indexOf('(')
                if (paren >= 0) {
                    val base = w.substring(0, paren)
                    val rest = w.substring(paren + 1)
                    if (base !in DB_SAFE_TYPE_WORDS || !rest.endsWith(")") ||
                        !Regex("^\\d+(\\s*,\\s*\\d+)*$").matches(rest.dropLast(1))
                    ) throw RuntimeException("Invalid column type component: " + w)
                } else if (!w.all { it.isDigit() } && w !in DB_SAFE_TYPE_WORDS) {
                    throw RuntimeException("Invalid column type component: " + w)
                }
            }
            if (defs.isNotEmpty()) defs.append(", ")
            defs.append("\"").append(name).append("\" ").append(typ)
        }
        database.execSQL("CREATE TABLE IF NOT EXISTS \"" + table + "\" (" + defs + ")")
        return true
    }

    fun dbTables(db: Any?): MutableList<String> {
        val database = db as android.database.sqlite.SQLiteDatabase
        val out = mutableListOf<String>()
        database.rawQuery(
            "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name", null,
        ).use { c -> while (c.moveToNext()) out.add(c.getString(0)) }
        return out
    }

    fun dbClose(db: Any?) {
        (db as? android.database.sqlite.SQLiteDatabase)?.close()
    }

    // ─── Sandboxed file bridge (file_* builtins) ───
    // Paths resolve inside the app's private filesDir; a bare name or relative path
    // never escapes the sandbox, matching Android's per-app storage model.
    private fun resolveFile(path: String): java.io.File {
        val base = EPLApplication.instance.applicationContext.filesDir
        val f = java.io.File(path)
        return if (f.isAbsolute) f else java.io.File(base, path)
    }

    fun fileExists(path: String): Boolean = resolveFile(path).exists()
    fun fileDelete(path: String): Boolean = resolveFile(path).let { if (it.exists()) it.delete() else false }
    fun fileRead(path: String): String = resolveFile(path).readText()
    fun fileWrite(path: String, content: Any?): Boolean {
        resolveFile(path).writeText(content?.toString() ?: "")
        return true
    }
    fun fileAppend(path: String, content: Any?): Boolean {
        resolveFile(path).appendText(content?.toString() ?: "")
        return true
    }
    fun fileSize(path: String): Long = resolveFile(path).let { if (it.exists()) it.length() else 0L }
}
